### ISSUE TITLE
Node.js 16 actions are deprecated !!! 

### ISSUE THREAD

**Issue by softproviding-brodmd** [MicroFocus/alm-octane-github-actions-integration#2]
I get a warning when running the action with this package: 

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: MicroFocus/alm-octane-github-actions-integration@v23.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

This should definitely get fixed to use this package in the future.

**Comment by Stefan923** [comment]
Hi,

The integration has been upgraded to Node.js 20 in v24.4.1.
