### ISSUE TITLE
New version is not available

### ISSUE THREAD

**Issue by AndersonGoulartRosa** [MicroFocus/alm-octane-github-actions-integration#4]
Trying to use the version v24.4.1 and is not available in marketplace, when it will be available ?

**Comment by Stefan923** [comment]
Hi Andreson,

The new version will be available soon. This release is still a draft. I will get back with an update on this issue when we complete this release.

**Comment by Stefan923** [comment]
Hi @AndersonGoulartRosa,

The new version is now available on the marketplace. (v24.4.1)
